/*1.Crear una vista llamada “MEDIOS_PAGO_CLIENTES” que contenga las siguientes columnas:
CLIENTE_ID, NOMBRE_CLIENTE (Si tiene el nombre y el apellido separados en columnas, deberán
estar unidas en una sola), MEDIO_PAGO_ID, TIPO (TDC, Android, Paypal, Efectivo),
DETALLES_MEDIO_PAGO, EMPRESARIAL (FALSO o VERDADERO), NOMBRE_EMPRESA (Si la
columna Empresarial es falso, este campo aparecerá Nulo) (0.25)*/


CREATE OR REPLACE VIEW MEDIOS_PAGO_CLIENTES AS
SELECT A.ID AS CLIENTE_ID,concat(A.NOMBRES ,A.APELLIDOS) AS NOMBRE_CLIENTE
,B.ID AS MEDIO_PAGO_ID, B.METODOS_PAGOS AS TIPO,
B.VALOR AS DETALLE_MEDIO_PAGO,
CASE A.TIPO_CLIENTE 
    WHEN 'EMPRESA' THEN 'VERDADERO'
    ELSE 'FALSO' END  AS EMPRESARIAL, 
CASE A.TIPO_CLIENTE 
    WHEN 'EMPRESA' THEN concat(A.NOMBRES ,A.APELLIDOS)
    ELSE null END  AS NOMBRE_EMPRESA 
FROM CLIENTES A 
INNER JOIN METODOS_PAGOS B ON A.ID=B.cliente_id ;


/*2. Cree una vista que permita listar los viajes de cada cliente ordenados cronológicamente. El nombre
de la vista será “VIAJES_CLIENTES”, los campos que tendrá son: FECHA_VIAJE,
NOMBRE_CONDUCTOR, PLACA_VEHICULO, NOMBRE_CLIENTE, VALOR_TOTAL,
TARIFA_DINAMICA (FALSO O VERDADERO), TIPO_SERVICIO (UberX o UberBlack),
CIUDAD_VIAJE. (0.25)*/


CREATE OR REPLACE VIEW VIAJES_CLIENTES as 
SELECT 
A.FECHA_INICIO_RECORRIDO AS FECHA_VIAJE, concat(B.NOMBRES ,B.APELLIDOS) AS NOMBRE_CONDUCTOR,
C.PLACA AS PLACA_VEHICULO, concat(D.NOMBRES ,D.APELLIDOS) AS NOMBRE_CLIENTE, E.VALOR_FACTURA AS VALOR_TOTAL,
CASE G.CONCEPTO 
WHEN 'COSTO_RECARGO' THEN 'VERDADERO'
ELSE 'FALSO' END  AS TARIFA_DINAMICA, 
C.VEHICULO AS TIPO_SERVICIO,
H.DESCRIPCION AS CIUDAD_VIAJE
FROM SERVICIOS A 
INNER JOIN CONDUCTORES B ON A.CONDUCTOR_ID= B.ID 
INNER JOIN VEHICULOS C ON A.VEHICULO_ID=C.ID 
INNER JOIN CLIENTES D ON A.CLIENTE_ID=D.ID 
INNER JOIN FACTURAS E ON A.ID=E.SERVICIO_ID 
INNER JOIN DETALLE_FACTURAS G ON E.ID=G.FACTURA_ID
INNER JOIN CIUDADES H ON A.CIUDAD_ID=H.ID
ORDER BY FECHA_INICIO_RECORRIDO
;

